//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FamilyConnext.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Connection
    {
        public int ConnectionID { get; set; }
        public int MemberID { get; set; }
        public string ConnectionDescription { get; set; }
        public int PointsAwarded { get; set; }
        public string FamilyID { get; set; }
    
        public virtual Member Member { get; set; }
    }
}
