//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FamilyConnext.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Milestone
    {
        public int MilestoneID { get; set; }
        public string MilestoneName { get; set; }
        public int PointsNeeded { get; set; }
        public string FamilyID { get; set; }
    }
}
